# Generated by Django 4.2.9 on 2024-01-18 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accelerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accelerator_id', models.CharField(max_length=15, unique=True)),
                ('accelerator_title', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('severity', models.CharField(choices=[('A', 'A'), ('B', 'B')], default='B', max_length=5)),
                ('is_assigned_to_engineer', models.BooleanField(default=False)),
                ('resolution_steps', models.TextField(blank=True, null=True)),
                ('position_in_company', models.CharField(choices=[('Co-founder', 'Co-founder'), ('Founder', 'Founder')], max_length=20)),
                ('applicant_name', models.CharField(max_length=255)),
                ('applicant_phone', models.CharField(max_length=15)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('problem_description', models.TextField(blank=True, null=True)),
                ('solution_description', models.TextField(blank=True, null=True)),
                ('serving_sectors', models.CharField(max_length=255)),
                ('competitors_description', models.TextField()),
                ('market_potential', models.TextField()),
                ('have_technical_documentation', models.BooleanField(default=False)),
                ('technical_documentation', models.TextField()),
                ('have_ursb_registration_number', models.BooleanField(default=False)),
                ('ursb_registration_number', models.CharField(max_length=50)),
                ('documented_processes', models.TextField()),
                ('have_documented_processes', models.BooleanField(default=False)),
                ('have_ura_registration_number', models.BooleanField(default=False)),
                ('ura_registration_number', models.CharField(max_length=50)),
                ('have_pdpo_registration_number', models.BooleanField(default=False)),
                ('pdpo_registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('funding_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('hub_requirements', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accelerators_customer', to=settings.AUTH_USER_MODEL)),
                ('engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='accelerators_engineer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
