# Generated by Django 4.2.9 on 2024-01-21 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accelerator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accelerator',
            old_name='is_assigned_to_engineer',
            new_name='is_assigned_to_officer',
        ),
        migrations.RemoveField(
            model_name='accelerator',
            name='engineer',
        ),
        migrations.AddField(
            model_name='accelerator',
            name='officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='accelerators_officer', to=settings.AUTH_USER_MODEL),
        ),
    ]
