# Generated by Django 4.2.9 on 2024-01-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0002_rename_is_assigned_to_engineer_accelerator_is_assigned_to_officer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accelerator',
            name='documented_processes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='accelerator',
            name='funding_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accelerator',
            name='hub_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='accelerator',
            name='technical_documentation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='accelerator',
            name='ura_registration_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accelerator',
            name='ursb_registration_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
