# Generated by Django 4.2.9 on 2024-01-21 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_engineer',
            new_name='is_officer',
        ),
    ]
