# Generated by Django 4.2.9 on 2024-01-16 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.CharField(max_length=15, unique=True)),
                ('complaint_title', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('severity', models.CharField(choices=[('A', 'A'), ('B', 'B')], default='B', max_length=5)),
                ('is_assigned_to_engineer', models.BooleanField(default=False)),
                ('resolution_steps', models.TextField(blank=True, null=True)),
                ('complainant_name', models.CharField(max_length=255)),
                ('complainant_phone', models.CharField(max_length=15)),
                ('is_submitted_for_another', models.BooleanField(default=False)),
                ('other_innovator_name', models.CharField(blank=True, max_length=255, null=True)),
                ('other_innovator_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('complaint_details', models.TextField()),
                ('is_first_time_submission', models.BooleanField()),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_customer', to=settings.AUTH_USER_MODEL)),
                ('engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='complaints_engineer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
