# Generated by Django 4.2.9 on 2024-01-22 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0003_rename_is_assigned_to_engineer_complaint_is_assigned_to_officer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='is_first_time_submission',
            field=models.BooleanField(default=False),
        ),
    ]
