# Generated by Django 4.2.9 on 2024-01-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0003_alter_incubator_documented_processes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incubator',
            name='funding_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
